array(2) {
    [0] => array(10) {
        [0] => array(14) {
            ["invId"] => string(16)
            "04I2IRQWSQ2QTYWT" ["invYear"] => int(2019)["invMake"] => string(7)
            "Hyundai" ["invModel"] => string(6)
            "Sonata" ["invDescription"] => string(222)
            "The 2019 Hyundai Sonata Hybrid is the more fuel-efficient version of the regular Sonata. It is powered by a combined 193-hp, 2.0-liter four-cylinder engine and an electric motor mated to a six-speed automatic transmission." ["invPrice"] => string(8)
            "35999.00" ["invMiles"] => int(32500)["invColor"] => string(11)
            "Light Brown" ["classificationId"] => int(8)["imgId"] => int(82)["imgName"] => string(27)
            "2019-hyundai-sonata-tn.webp" ["imgPath"] => string(54)
            "/phpmotors/images/vehicles/2019-hyundai-sonata-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:19:34" ["imgPrimary"] => int(1)
        } [1] => array(14) {
            ["invId"] => string(16)
            "2WK9RTS7O68VFKWD" ["invYear"] => int(2019)["invMake"] => string(8)
            "Chrysler" ["invModel"] => string(4)
            "300S" ["invDescription"] => string(206)
            "This Chrysler 300 S comes with Leather Seats, Alpine Sound System, Rear View Camera, Navigation System, Front Seat Heaters, A/C Seat(s) Automatic Transmission. Ride in comfort in this classic looking sedan." ["invPrice"] => string(8)
            "26998.00" ["invMiles"] => int(40014)["invColor"] => string(4)
            "Blue" ["classificationId"] => int(7)["imgId"] => int(70)["imgName"] => string(25)
            "2019-chrysler-300-tn.webp" ["imgPath"] => string(52)
            "/phpmotors/images/vehicles/2019-chrysler-300-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:17:31" ["imgPrimary"] => int(1)
        } [2] => array(14) {
            ["invId"] => string(16)
            "3T2TTTT42HN01GVD" ["invYear"] => int(2019)["invMake"] => string(7)
            "Hyundai" ["invModel"] => string(7)
            "Elantra" ["invDescription"] => string(259)
            "The 2019 Hyundai Elantra is a compact sedan that has been refreshed with a more angular appearance and sharp triangular headlights. It is powered by a 128-hp, turbocharged 1.4-liter four-cylinder joined to a seven-speed dual-clutch automatic in this ECO trim." ["invPrice"] => string(8)
            "19590.00" ["invMiles"] => int(34109)["invColor"] => string(3)
            "Red" ["classificationId"] => int(7)["imgId"] => int(80)["imgName"] => string(28)
            "2019-hyundai-elantra-tn.webp" ["imgPath"] => string(55)
            "/phpmotors/images/vehicles/2019-hyundai-elantra-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:19:06" ["imgPrimary"] => int(1)
        } [3] => array(14) {
            ["invId"] => string(16)
            "4K6WT4KJWS8D1K4Z" ["invYear"] => int(2019)["invMake"] => string(4)
            "Ford" ["invModel"] => string(6)
            "Taurus" ["invDescription"] => string(378)
            "The Taurus has one of the 10 Best Engines in vehicles today. It scores 29 Highway MPG and 19 City MPG! This Ford Taurus delivers a Gas V6 3.5L/213 engine powering this Automatic transmission. Vinyl-wrapped front center console -inc: armrest, front covered cupholders/storage bin, removable trinket tray, painted appliques, Universal garage door opener, Torque vectoring control." ["invPrice"] => string(8)
            "18195.00" ["invMiles"] => int(28951)["invColor"] => string(6)
            "Silver" ["classificationId"] => int(7)["imgId"] => int(76)["imgName"] => string(24)
            "2019-ford-taurus-tn.webp" ["imgPath"] => string(51)
            "/phpmotors/images/vehicles/2019-ford-taurus-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:18:29" ["imgPrimary"] => int(1)
        } [4] => array(14) {
            ["invId"] => string(16)
            "DXEU3TCEN4OL119O" ["invYear"] => int(2019)["invMake"] => string(7)
            "Porsche" ["invModel"] => string(6)
            "Cayman" ["invDescription"] => string(212)
            "A siren on wheels. It will lure you to the road, and you will never look back! The Cayman\'s joyful driving demeanor, powerful flat-four engines, and stunning styling make it a favorite for sports car enthusists." ["invPrice"] => string(8)
            "65000.00" ["invMiles"] => int(71222)["invColor"] => string(12)
            "Metalic blue" ["classificationId"] => int(3)["imgId"] => int(104)["imgName"] => string(27)
            "2019-porsche-cayman-tn.webp" ["imgPath"] => string(54)
            "/phpmotors/images/vehicles/2019-porsche-cayman-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 17:10:05" ["imgPrimary"] => int(1)
        } [5] => array(14) {
            ["invId"] => string(16)
            "DYDNKCN15NSTNJOK" ["invYear"] => int(2019)["invMake"] => string(4)
            "Ford" ["invModel"] => string(4)
            "F250" ["invDescription"] => string(242)
            "This Ford F250 Lariat with Long Bed, Bed Cover, 4WD/AWD, Leather Seats, Satellite Radio Ready, Parking Sensors. and Automatic transmission is ready to be put to work. It is a tough truck, but drives and rides like a luxury car. Come drive it." ["invPrice"] => string(8)
            "59998.00" ["invMiles"] => int(22351)["invColor"] => string(3)
            "Red" ["classificationId"] => int(4)["imgId"] => int(74)["imgName"] => string(22)
            "2019-ford-f250-tn.webp" ["imgPath"] => string(49)
            "/phpmotors/images/vehicles/2019-ford-f250-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:18:09" ["imgPrimary"] => int(1)
        } [6] => array(14) {
            ["invId"] => string(16)
            "FHSCZ7MKMZG6ER8H" ["invYear"] => int(2019)["invMake"] => string(10)
            "Volkswagen" ["invModel"] => string(5)
            "Jetta" ["invDescription"] => string(229)
            "2019 Volkswagen Jetta S with Turbo Charged Engine, Rear View Camera, Cruise Control, Auxiliary Audio Input, Alloy Wheels, Overhead Airbags. Transmission: Manual 6 Speed transmission. Sporty and responsive, come take a test drive." ["invPrice"] => string(8)
            "18998.00" ["invMiles"] => int(25645)["invColor"] => string(4)
            "Blue" ["classificationId"] => int(7)["imgId"] => int(86)["imgName"] => string(29)
            "2019-volkswagen-jetta-tn.webp" ["imgPath"] => string(56)
            "/phpmotors/images/vehicles/2019-volkswagen-jetta-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:20:13" ["imgPrimary"] => int(1)
        } [7] => array(14) {
            ["invId"] => string(16)
            "JD876EAQE8FKB0MZ" ["invYear"] => int(2019)["invMake"] => string(7)
            "Porsche" ["invModel"] => string(3)
            "911" ["invDescription"] => string(252)
            "2019 Porsche 911 Turbo Coupe AWD with Leather Seats, Sunroof/Moonroof, Navigation System, Alloy Wheels, Adaptive Suspension, Memory Package, Backup Camera, CarPlayCertified and 7-Speed Automatic transmission. Take a ride and feel the power and comfort." ["invPrice"] => string(9)
            "175900.00" ["invMiles"] => int(3975)["invColor"] => string(15)
            "Metallic Orange" ["classificationId"] => int(3)["imgId"] => int(84)["imgName"] => string(24)
            "2019-porsche-911-tn.webp" ["imgPath"] => string(51)
            "/phpmotors/images/vehicles/2019-porsche-911-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:19:54" ["imgPrimary"] => int(1)
        } [8] => array(14) {
            ["invId"] => string(16)
            "MZ4KKYUUV6KTID7C" ["invYear"] => int(2019)["invMake"] => string(5)
            "Honda" ["invModel"] => string(7)
            "Insight" ["invDescription"] => string(214)
            "2019 Honda Insight EX Sedan FWD with Adaptive Cruise Control, Alloy Wheels, Bluetooth, Backup Camera, Android Auto, CarPlay, Continuously Variable Transmission and hybrid electric motor assist. Economical to drive." ["invPrice"] => string(8)
            "24200.00" ["invMiles"] => int(28815)["invColor"] => string(3)
            "Red" ["classificationId"] => int(8)["imgId"] => int(78)["imgName"] => string(26)
            "2019-honda-insight-tn.webp" ["imgPath"] => string(53)
            "/phpmotors/images/vehicles/2019-honda-insight-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:18:48" ["imgPrimary"] => int(1)
        } [9] => array(14) {
            ["invId"] => string(16)
            "R4QPNEYB8FR04MH0" ["invYear"] => int(2019)["invMake"] => string(8)
            "Cadillac" ["invModel"] => string(8)
            "Escalade" ["invDescription"] => string(150)
            "This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home." ["invPrice"] => string(8)
            "75195.00" ["invMiles"] => int(48951)["invColor"] => string(5)
            "Black" ["classificationId"] => int(6)["imgId"] => int(22)["imgName"] => string(30)
            "2019-cadillac-escalade-tn.webp" ["imgPath"] => string(57)
            "/phpmotors/images/vehicles/2019-cadillac-escalade-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 15:17:22" ["imgPrimary"] => int(1)
        }
    } [1] => array(2) {
        [0] => array(14) {
            ["invId"] => string(16)
            "VYJNBY0DOWFY8ISO" ["invYear"] => int(2019)["invMake"] => string(4)
            "Ford" ["invModel"] => string(6)
            "Escape" ["invDescription"] => string(222)
            "This Ford Escape SE AWD comes with Adaptive Cruise Control, Alloy Wheels, Bluetooth, Backup Camera, Blind Spot Monitoring, Heated Seats and a 6-Speed Automatic transmission. It is super clean and ready to go home with you." ["invPrice"] => string(8)
            "14995.00" ["invMiles"] => int(68521)["invColor"] => string(5)
            "White" ["classificationId"] => int(1)["imgId"] => int(72)["imgName"] => string(24)
            "2019-ford-escape-tn.webp" ["imgPath"] => string(51)
            "/phpmotors/images/vehicles/2019-ford-escape-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 16:17:51" ["imgPrimary"] => int(1)
        } [1] => array(14) {
            ["invId"] => string(16)
            "WJHXR08G8OOVS0US" ["invYear"] => int(2019)["invMake"] => string(7)
            "Hyundai" ["invModel"] => string(5)
            "Venue" ["invDescription"] => string(40)
            "Dependable, great economy, tons of room." ["invPrice"] => string(8)
            "29000.00" ["invMiles"] => int(12689)["invColor"] => string(4)
            "Blue" ["classificationId"] => int(1)["imgId"] => int(102)["imgName"] => string(26)
            "2019-hyundai-venue-tn.webp" ["imgPath"] => string(53)
            "/phpmotors/images/vehicles/2019-hyundai-venue-tn.webp" ["imgDate"] => string(19)
            "2021-11-24 17:09:36" ["imgPrimary"] => int(1)
        }
    }
}